services:
  nginx:
    build:
      context: .
      dockerfile: .docker/nginx/Dockerfile

    restart: unless-stopped

    depends_on:
      - php

    volumes:
      - .:/var/www/html

    ports:
      - "80:80"
      - "443:443"

    networks:
      - internal

  php:
    build:
      context: .
      dockerfile: .docker/php/Dockerfile

    restart: unless-stopped

    volumes:
      - .:/var/www/html

    expose:
      - "9000"

    environment:
      XDEBUG_MODE: "off"

networks:
  internal:
    driver: bridge